# Generated by Django 3.2.15 on 2023-02-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pojazd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapytanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zapytanie_id', models.CharField(max_length=50)),
                ('imie', models.CharField(max_length=50)),
                ('nazwisko', models.CharField(max_length=50)),
                ('regon', models.CharField(max_length=50)),
                ('urodzenie_data', models.DateField(null=True)),
                ('rozpoczecie_polisy_data', models.DateField()),
                ('pojazd', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pojazd.pojazd')),
            ],
        ),
    ]
