# Generated by Django 3.2.15 on 2023-02-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pojazd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marka', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('rocznik', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
