# Generated by Django 3.2.15 on 2023-02-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zakres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokrycie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=50)),
                ('ubezpieczenie_suma', models.PositiveIntegerField()),
                ('zakres', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='zakres.zakres')),
            ],
        ),
    ]
